Renamed service package to rest in -Order
devonfw-sample/devon4quarkus-order pull request #7
Opened 2021-11-25 12:11 UTC by rafaelvicariabarker

2021-11-29 09:14 UTC, GuentherJulian approved these changes

2021-11-29 12:19 UTC, GuentherJulian requested changes

2021-11-29 12:19 UTC, GuentherJulian commented on src/test/java/com/devonfw/quarkus/ordermanagement/rest/v1/OrderRestServiceTest.java
> -package com.devonfw.quarkus.ordermanagement.service.v1;
In line 25 and 26 there are still imports with package name `service.v1`

2021-11-29 12:19 UTC, GuentherJulian commented on src/main/java/com/devonfw/quarkus/ordermanagement/logic/UcFindOrder.java
> +dpackage com.devonfw.quarkus.ordermanagement.logic;
Typo

2021-11-29 12:36 UTC, GuentherJulian approved these changes

2021-12-01 09:44 UTC, maybeec approved these changes

2021-12-01 09:44 UTC, merged